### PR TITLE
Evaluate ordering of callbacks when socket notifiers are part of the play

### PR DESCRIPTION
**Pull request by horazont**
This is about a divergence from the behaviour of the default Selector based event loop, as used e.g. on ArchLinux and Fedora (others too, but I have not verified these). The test case which gets added by this pull request runs fine on those and fails when using QEventLoop from Quamash. For convenience, the code of the test case is here (it differs slightly from that in #24):

	def test_scheduling(loop, sock_pair):
		s1, s2 = sock_pair
		fd = s1.fileno()
		cb_called = asyncio.Future()
	
		def writer_cb(fut):
			if fut.done():
				cb_called.set_exception(
					ValueError("writer_cb called twice")
				)
			fut.set_result(None)
	
		def fut_cb(fut):
			loop.remove_writer(fd)
			cb_called.set_result(None)
	
		fut = asyncio.Future()
		fut.add_done_callback(fut_cb)
		loop.add_writer(fd, writer_cb, fut)
		loop.run_until_complete(cb_called)
	

In stock asyncio, the following happens:

1. After the setup, writer_cb gets called (as the socket is obviously writable). It sets the futures result to `None`.
2. ``fut_cb`` gets called; it detaches the ``writer_cb`` and sets the result future ``cb_called``, thus the loop is going to terminate soon.
3. Loop terminates cleanly.

With Quamash, the following happens instead:

1. After the setup, writer_cb gets called (as the socket is obviously writable). It sets the futures result to `None`.
2. ``writer_cb`` is called again immediately. The future being done already, it sets the result future ``cb_called`` to an exceptional state (to terminate the test with a loud bang).
3. Test fails.

This is critical, as ``sock_connect`` from the asyncio version shipping with Python 3.4.2 relies on this behaviour, as you can see from the following snippet copied from selector_events.py:

        def _sock_connect(self, fut, sock, address):
            fd = sock.fileno()
            try:
                while True:
                    try:
                        sock.connect(address)
                    except InterruptedError:
                        continue
                    else:
                        break
            except BlockingIOError:
                fut.add_done_callback(functools.partial(self._sock_connect_done,
                                                        sock))
                self.add_writer(fd, self._sock_connect_cb, fut, sock, address)
            except Exception as exc:
                fut.set_exception(exc)
            else:
                fut.set_result(None)
    
        def _sock_connect_done(self, sock, fut):
            self.remove_writer(sock.fileno())
    
        def _sock_connect_cb(self, fut, sock, address):
            if fut.cancelled():
                return
    
            try:
                err = sock.getsockopt(socket.SOL_SOCKET, socket.SO_ERROR)
                if err != 0:
                    # Jump to any except clause below.
                    raise OSError(err, 'Connect call failed %s' % (address,))
            except (BlockingIOError, InterruptedError):
                # socket is still registered, the callback will be retried later
                pass
            except Exception as exc:
                fut.set_exception(exc)
            else:
                fut.set_result(None)

There is more code around it, but when BlockingIOError gets raised and caught in _sock_connect, basically the same thing as in the provided test case happens. The result is that in applications using sock_connect (which is used under the hood by things like create_connection), if the connection cannot get established right away, weird behaviour encurs, which at least involves a lot of exception tracebacks being printed.

I see that this is hard to fix with Qt, as we don’t have full control about when callbacks from Qt get called. This is what I think may serve as a patch to this:

* In ``__on_notifier_ready``, we would use call_soon instead of directly calling the callback.
* In addition, not the callback is scheduled via call_soon, but a wrapper which takes care of re-enabling the notifier if required after the callback returns (or raises).
* During that, the notifier is disabled.

I have not implemented or tested this yet, but I’ll have a go on it now. Posting this here in case someone has a strong opinion on that topic.

### CODE REVIEW

**Comment by horazont** [comment]
I have a possible solution, but it requires changes currently only in the depinject branch. I have cherry-picked these and pushed my branch. I plan to rebase my branch on master when depinject has landed (which is passing all tests at my site (Fedora Linux with PyQt5) btw.).

**Comment by harvimt** [comment]
well those fixes could be merged back into master (as one commit) since they don't have anything to do with the features added in depinject. I might just do that.

I think I have some other commits I want to pull over from depinject.

**Comment by harvimt** [comment]
Also note that the appveyor tests fail for everyone at the moment. It would be nice if they passed though.

**Comment by horazont** [comment]
@harvimt How’s the progress on pulling some of the non-depinject related changes from depinject into master? I’d like to rebase this to get it merged. 

Although I understand if you want to get CI working first, good test coverage is always a nice thing to have before advancing.

**Comment by horazont** [comment]
Oh, I just realize that you did the merge (checked the history manually). It’d be great if you could do the merges in a way github notes that they are done, or manually mark it as merged / closed. I think this requires to use git merge so that the commit IDs stay intact.

**Comment by harvimt** [comment]
yeah probably, I like a clean commit history on master without all the "oops typo" changes  in it. and the depinject branch is filled with those + one big gnarly commit.
But yeah, using rebase or cherry-pick kills the commit id.

I just forgot to close this. And it would explain why in #27 @sfrazt had problems with 0.4.1 but not the master version.

I definitely should have closed this earlier though.

**Comment by horazont** [comment]
I understand having a clean history without "oops typos" makes sense, I like that too.

How about rebasing feature branches (such as depinject) before merging, and avoiding to do error-prone work on (public) master? That would avoid these issues. 

Sorry for keeping the topic open, but I think this is important and it gets even more important when more users are attracted to quamash.

**Comment by harvimt** [comment]
It *is* important. This has been a big experiment for me and I'm definitely learning how ignorant I am at some sorts of software engineering tasks. A decade of cowboy coding hasn't provided me with the need to merge other people's commits very often.

**Pull request closed without merging**
