### PR TITLE
Timeout tests when they hang.

### PR DESCRIPTION
**Pull request by Korijn**
Hopefully this will snuff out the test that times out on AppVeyor.

* Added pytest-timeout
* Configured test timeout to 10s
* Added .vscode to gitignore

Continuation of #74

### CODE REVIEW

**Comment by Korijn** [comment]
Looks like the test suite at least completes now, instead of timing out the AppVeyor build... now to figure out which one it is!

**Comment by Korijn** [comment]
It's `test_can_execute_subprocess_primitive`

**Comment by Korijn** [comment]
Oddly enough there seem to be race conditions at work:

image

One passed, two failed, and one is hanging indefinitely, even with pytest-timeout...

**Comment by Korijn** [comment]
I'm not seeing any failing tests anymore. But AppVeyor still returns with a nonzero exit code. What could be the root cause?

**Comment by Korijn** [comment]
Perhaps we need to use pytest-xdist's option `--boxed`...

**Comment by Korijn** [comment]
I've configured pytest-xdist to box all tests in isolated subprocesses, and I've removed the skip markers. Let's see if that will give us a decent overview of test failures...

**Comment by harvimt** [comment]
Yeah I came accross this before, boxed still isn't supported on windows:
https://bitbucket.org/pytest-dev/pytest/issues/193/xdist-support-for-boxed-on-windows

On Thu, Aug 10, 2017 at 11:41 PM, Korijn van Golen <notifications@github.com

**Comment by Korijn** [comment]
Alright, so, what I've learned in this process is that:

* All tests randomly fail on Windows, so test skip decorators don't make any sense. Therefore I've removed the decorator I added in a previous PR.
* Boxing tests to subprocesses with pytest-xdist is not supported in Windows, so that doesn't help either.
* I added pytest-timeout to make sure AppVeyor doesn't hang indefinitely.

This PR can be merged as is, but it won't help getting AppVeyor builds to pass. Someone really needs to dig into the internals of the library and the tests to figure out what is going on.

**Comment by Korijn** [comment]
@harvimt Can this be merged?

**Pull request merged**
