### PR TITLE
Added Python 3.6 to CI

### LINKED ISSUE #72: python 3.6?
Any efforts going on to support python 3.6? Are you accepting PRs?

### PR DESCRIPTION
**Pull request by Korijn**
* Added Python 3.6 to CI
* Also adds Python 3.5 to AppVeyor since it was missing

Resolves #72

### CODE REVIEW

**Comment by Korijn** [comment]
Rebased on master.

**Comment by harvimt** [comment]
You need to download the PyQt 5.5

by modifying: https://github.com/harvimt/quamash/blob/master/.travis.yml#L14 as well as the md5sum

**Comment by harvimt** [comment]
Actually, it looks like PyQt5.5 is available as a wheel on PyPI for Python 3.5, so it can just be pip installed. Older versions of PyQt are not available as wheels though.

We can build our own wheel for py 3.6 and put it in the wheelhouse directory, (like I did for PySide).

**Comment by harvimt** [comment]
I bet the wheels are statically linked to so we don't need to `apt-get install` qt5

**Comment by harvimt** [comment]
nm again, PyQt 5.9 is available as a "manylinux" py 3.5,3.6,3.7 multi-wheel

https://pypi.python.org/pypi/PyQt5/5.9

**Comment by Korijn** [comment]
That would mean dropping support for Python 3.3 and 3.4 then? I'll try and extend the current approach a bit more, before I totally swing everything around...

**Comment by Korijn** [comment]
Python 3.4, 3.5 and 3.6 passed now. Python 3.3 seems to fail because PyQt5 doesn't support it anymore. Should we follow suit and drop it?

**Comment by harvimt** [comment]
I think the python foundation dropped support for python 3.3 as well (as in
it's not receiving even security patches), so that's probably a good call.

**Comment by Korijn** [comment]
I'm OK with merging this.

**Comment by harvimt** [comment]
Alright, to actually update the little badge, the trove specifiers in setup.py need to be changed.

Then the version needs to be bumped (with a change log entry in the README).

Then I can upload a new version to PyPI and then supported versions will be updated.

**Pull request merged**
