### PR TITLE
Minor Changes for 3.7 Compatability

### PR DESCRIPTION
**Pull request by henry232323**
Pretty self explainable I think

### CODE REVIEW

**Comment by harvimt** [comment]
PR won't be merged until the tests pass.

**Comment by harvimt** [comment]
Sorry I hadn't even looked at the build logs. I ignored this PR since I knew I would have to fix the tests, but looking at it, they're actually all passing (as well as they were) except the style checker.

The AppVeyor tests are actually passing as well as they always have. Travis tests are failing with `./setup.py:20:22: C819 trailing comma prohibited`  which seems to be a new feature check added to flake8-comma, but it's a good one, please change `packages=['quamash', ],` in setup.py to `packages=['quamash'],` to fix this.

Additionally, you're changing all my precious tabs to spaces, please change the spaces back to tabs, and fix the comma, and that should be sufficient for a merge + upload.

If your editor automatically turns tabs to spaces, please find one which is compatible with "editorconfig" config files.

**Comment by henry232323** [comment]
PyQt4 fails on 3.6, 3.5, and 3.4 for lack of an available version
Sip fails on 3.4 for PyQt5
Lord knows whats happening with PySide for 3.4
```py
quamash\__init__.py ..                                                   [  4%]
tests\test_qeventloop.py ........................................        [ 93%]
tests\test_qthreadexec.py ...                                            [100%]
========================== 45 passed in 7.62 seconds ==========================
Command exited with code -1073741819
```
This all being just for the appveyor checks

**Comment by harvimt** [comment]
Yeah I spent several hours looking at the PySide tests on Windows awhile ago and couldn't figure them out, someone pointed out the exit code is a windows error code (convert negative number to unsigned hex) for [0xc0000005 Access Violation](https://stackoverflow.com/questions/5303524/what-exactly-is-the-scope-of-access-violation-0xc0000005)

```
>>> hex(-1073741819 + 2**32)
'0xc0000005'
```

Anyway, tests are passing, whitespace is back in order (probably my fault for letting it drift to half spaces half tabs oops).

Would be good to add tests for 3.7 since that's the intent of this PR, but as it is at least it's not making anything worse, and it gets rid of `__import__` which was deprecated even when I wrote that code.

**Pull request merged**
