### PR TITLE
Fix issue #34

### PR DESCRIPTION
**Pull request by Insoleet**
Gotcha ! 

So there were to references to remove : timer and handle in the callback instance. Please check the validity of my code but it should be ok.

### CODE REVIEW

**Comment by harvimt** [comment]
The tests are not passing in CI, though they are passing locally for me (on linux)

Looks like there are some problems with appveyor and broken URLs? I'll fix them in master and then rebase.

**Comment by harvimt** [comment]
Note that the Circle CI tests don't work, I haven't actually set them up yet...

The Travis builds are failing on both the "use quamash" and "don't use quamash" state, so it's probably something weird. I'd like to see passing tests on windows, but it's hard to see how this could make it worse.

**Comment by Insoleet** [comment]
I wonder why the tests are passing locally but not on Travis ? May it be related to https://docs.python.org/3.4/library/gc.html#gc.garbage , where before python 3.4, objects with a __del__ method could not be deleted by the garbage collector ?

**Comment by harvimt** [comment]
Travis is running both Python 3.4 and Python 3.3 tests and both fail... so
that's not it.

**Comment by Insoleet** [comment]
On python 3.4, it's only flake8 which fails. The test is passing. 
https://travis-ci.org/harvimt/quamash/jobs/76489498

**Comment by harvimt** [comment]
Hrm. Using `del x` instead of `x = None` didn't work either.

**Comment by harvimt** [comment]
(I hindsight I don't know why it would have)

**Comment by Insoleet** [comment]
The problem is that the custom \__del\__ is never called on the Task for Python 3.3. The Task is deleted but the exception handler is not called.  
I'm not sure what should be done. Maybe just disable the test for python < 3.4...

**Comment by harvimt** [comment]
Alright, I marked the test as xfail on python 3.3, did a little minor rebasing. I'm probably ready to push a bugfix release to PyPI.

**Comment by Insoleet** [comment]
That'd be perfect :)

**Pull request merged**
